service: loaSocketServerless

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  apiName: loaSocketServerlessDev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  LOA_postSocket:
    handler: src/index.handler
    events:
      - http:
          path: /yrdy
          method: post
  crawlDataFromTrader:
    handler: src/crawDataFromTraderIndex.handler
    events:
      - http:
          path: /cdft
          method: post
